### ISSUE TITLE
Separate turn on commands can be improved

### ISSUE THREAD

**Issue by edobez** [basnijholt/adaptive-lighting#49]
I'm trying to apply the (great) AL to my IKEA color bulb, without much success.
I had problems already with that in the past, since it can't make a transition with just on service call when it contains both brightness and color transitions.

I can imagine that the option 'separate_turn_on_commands' are made for such occasions, but it fails to do its job in this case. I think the problem is that the two service calls are made too close to each other. Probably they need to wait at least the 'transition' time.

I can provide more details if needed.

**Comment by basnijholt** [comment]
> I think the problem is that the two service calls are made too close to each other.

Unfortunately, I cannot test this, so I would need to be sure what the problem is before I can implement it.

> I can imagine that the option 'separate_turn_on_commands' are made for such occasions

Indeed you are correct!

**Comment by edobez** [comment]
> Unfortunately, I cannot test this, so I would need to be sure what the problem is before I can implement it.

The problem is that the bulb is unresponsive while making a transition, so the subsequent commands are not received - or at least executed. This means that there must be a delay between the first and second `light.turn_on` calls. I assume a little longer than the transition is enough.

I can even try to make the code change and test it myself, then open a PR.

**Comment by apmillen** [comment]
I have been having a similar issue with my IKEA white tunable bulbs.
I had a script before which would send two light.turn_on commands with a delay in the middle which was the same as the transition of the first light.turn_on command.

Always worked without an issue.

**Comment by basnijholt** [comment]
Hi @edobez, @apmillen, @dedepene, @psbankar (from #29),

I have implemented that there is a pause between `turn_on` commands of `transition/2` if `separate_turn_on_commands` is used. Please update to the latest version and report whether it's working for you now.

**Comment by basnijholt** [comment]
I will close this issue for now (assuming it's fixed). Let me know if this is not the case, then I will reopen.

**Comment by mhoellmann** [comment]
Unfortunately this did not resolve the problem. I think the problem is that the first transition is still ongoing when the command for the second transition arrives at the bulb. The general problem is also described [here](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/445#issuecomment-373649142). 

I guess it would be the easiest to separate the transition of the color and the transition of the brightness by the interval time between switch updates (assuming that interval time >> transition time). Or there must a be another kind of buffer between the end of the first and the start of the second transition.

**Comment by apmillen** [comment]
Agreed - works perfectly with my Ikea bulbs when they are on but the initial turn on still doesn't work as expected.
Looks like the the light.turn_on colour temp command sends before the light has completed the light.turn_on brightness command.

I have put a work around in as an automation which currently means it works as I would like.

```
alias: dining_room_adaptive_control
id: e39bb266-44b3-46e2-bdb6-324ca45fb843
mode: restart

trigger:
  - platform: state
    entity_id: light.dining_room_lamp
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: light.dining_room_lamp
    from: 'on'
    to: 'off'

condition: []

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'on' }}"
        sequence:
          - delay:
              milliseconds: 500
          - service: light.turn_on
            data:
              entity_id: light.dining_room_lamp
              brightness_pct: "{{ state_attr('switch.adaptive_lighting_dining_room', 'brightness_pct') | round }}"
              transition: 2
          - delay:
              seconds: 2
          - service: light.turn_on
            data:
              entity_id: light.dining_room_lamp
              kelvin: "{{ state_attr('switch.adaptive_lighting_dining_room', 'color_temp_kelvin') | int }}"
              transition: 2
          - delay:
              seconds: 2
          - service: switch.turn_on
            data:
              entity_id:
                - switch.adaptive_lighting_adapt_brightness_dining_room
                - switch.adaptive_lighting_adapt_color_dining_room
      - conditions: 
          - condition: template
            value_template: "{{ trigger.to_state.state == 'off' }}"
        sequence:
          - service: switch.turn_off
            data:
              entity_id:
                - switch.adaptive_lighting_adapt_brightness_dining_room
                - switch.adaptive_lighting_adapt_color_dining_room
```

**Comment by thesymbol** [comment]
Had the same problem with turn on, thank you for the automation workaround.
I made it into a blueprint so its easily configurable which light/light group and switches to use. (didn't add adjustments to the transitions tho since i thought they were good).

```
blueprint:
  name: Adaptive_lighting - IKEA turn on/off workaround.
  description: |
    Workaround for turning on and off ikea lights with adaptive_lighting.

  domain: automation
  input:
    light_to_use:
      name: Light / light group
      description: The light or light group (could use comma seperated string as well)
      selector:
        entity:
          domain: light
    adaptive_lighting_main_switch:
      name: Adaptive Lighting main switch
      description: The main switch
      selector:
        entity:
          domain: switch
    adaptive_lighting_adapt_brightness_switch:
      name: Adaptive Lighting adapt_brightness switch
      description: The adaptive_lighting_adapt_brightness switch
      selector:
        entity:
          domain: switch
    adaptive_lighting_adapt_color_switch:
      name: Adaptive Lighting adapt_color switch
      description: The adaptive_lighting_adapt_color switch
      selector:
        entity:
          domain: switch

mode: restart

trigger:
  - platform: state
    entity_id: !input "light_to_use"
    from: "off"
    to: "on"
  - platform: state
    entity_id: !input "light_to_use"
    from: "on"
    to: "off"

action:
  - variables:
      main_switch: !input "adaptive_lighting_main_switch"
      bri_pct: "{{ state_attr(main_switch, 'brightness_pct') | round }}"
      kelv: "{{ state_attr(main_switch, 'color_temp_kelvin') | int }}"
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'on' }}"
        sequence:
          - delay:
              milliseconds: 500
          - service: light.turn_on
            data:
              entity_id: "{{trigger.entity_id}}"
              brightness_pct: "{{bri_pct}}"
              transition: 2
          - delay:
              seconds: 2
          - service: light.turn_on
            data:
              entity_id: "{{trigger.entity_id}}"
              kelvin: "{{kelv}}"
              transition: 2
          - delay:
              seconds: 2
          - service: switch.turn_on
            data:
              entity_id:
                - !input "adaptive_lighting_adapt_brightness_switch"
                - !input "adaptive_lighting_adapt_color_switch"
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'off' }}"
        sequence:
          - service: switch.turn_off
            data:
              entity_id:
                - !input "adaptive_lighting_adapt_brightness_switch"
                - !input "adaptive_lighting_adapt_color_switch"
```

**Comment by edobez** [comment]
Those automation workarounds work very well!
I can add one additional refactoring that I have done. This is extracting the central part of the sequence, so that it can be reused in other situations. I personally use that script for applying presets (like scenes).
```
alias: delayed_turn_on
description: |
  Workaround for setting both brightness and kelvin on an IKEA Tradfri color bulb
fields:
  light_id:
    description: Target light
    example: light.tradfri_bulb
  kelvin:
    description: Kelvin temperature to set
    example: 5000
  brightness_pct:
    description: Brightness percentage to set
    example: 80
  transition:
    description: Transition time
    example: 5
variables:
  delay_time: 100
sequence:
  - alias: "Set color temp"
    service: light.turn_on
    target:
      entity_id: "{{ light_id }}"
    data_template:
      kelvin: "{{ kelvin }}"
      transition: "{{ transition | float / 2 }}"
  - alias: "Wait half transition time"
    delay: 
      milliseconds: "{{ transition | float / 2 * 1000 + delay_time }}"
  - alias: "Set brightness"
    service: light.turn_on
    target:
      entity_id: "{{ light_id }}"
    data_template:
      brightness_pct: "{{ brightness_pct }}"
      transition: "{{ transition | float / 2 }}"
```

**Comment by mlangenberg** [comment]
@edobez Can you share a full example on how to use this workaround for the adaptive lighting addon? 

Currently I have just set `initial_transition` and `transition` to 0. But I would like a short (1 second) transition when my lights turn on. I'm not sure how your `delayed_turn_on` hooks into the `adaptive_lighting` configuration.

**Comment by edobez** [comment]
@mlangenberg It took me some time to remember/check my current configuration since I didn't change it since March!

I'll write just a short recap so it will be easier to follow.
IKEA bulbs have the problem that can't be turned on with a command that specifies both brightness and color temperature. AL manages to solve this problem by having the option `separate_turn_on_commands`, which works well when the bulb is already on.
However the problem remains when there is a transition between off->on. For some reason the previous option doesn't solve this problem, but my workaround does exactly that. It is composed of two parts:
1. `delayed_turn_on` service, which sends two `light.turn_on` commands in a sequence separated by a configurable delay, which respectively sets the color temperature and the brightness.
2. `adaptive_lighting_ikea_tradfri` automation, which checks for off->on and on->off transitions. 
   - In the off->on case it calls the `delayed_turn_on` service, waits a bit, and then enabled AL for that light
   - In the on->off case it disables AL for that light, so in the next off->on transition AL won't take over

Now, I don't know if in the last months there were any updates to AL or IKEA firmware that makes this workaround obsolete or not working. I can only say that it works for me.
The relevant part of my AL configuration is:
- `initial_transition`: 1
- `transition_time`: 2
- `interval`: 90

I'm attaching the script and blueprint/automation.
[adaptive_lighting_ikea_tradfri.yaml.txt](https://github.com/basnijholt/adaptive-lighting/files/7613205/adaptive_lighting_ikea_tradfri.yaml.txt)
[delayed_turn_on.yaml.txt](https://github.com/basnijholt/adaptive-lighting/files/7613206/delayed_turn_on.yaml.txt)

**Comment by mlangenberg** [comment]
Great! Thanks a lot! I just bought the most recent [TRÅDFRI E27 1055 lumen](https://www.ikea.com/nl/en/p/tradfri-led-bulb-e27-1055-lumen-wireless-dimmable-white-spectrum-globe-opal-white-40486783/) (model TRADFRIbulbE27WSglobeopal1055lm, version 1.0.012) bulbs and they still present the same issue.

I'm going to give your workaround a shot before I return them and buy Philips Hue White Ambiance bulbs instead. 

I assume you are disabling AL on the on→off transition, to 'intercept' when the light is turned back on again. So you can manually set the brightness and color in a sequence with the `delayed_turn_on` script, right? But wouldn't this disable AL for all lights under control of that AL switch? 

Maybe `adaptive_lighting.set_manual_control` could be used instead of turning off the entire AL switch.

**Comment by mlangenberg** [comment]
I wrote a small script using the deCONZ REST-API sending the following commands:

- Set bulb to warm soft light; then turn it off (initial state)
- Turn bulb on; set full brightness; transition 1 second
- Sleep 1 second
- Set bulb to cool temperature; transition 1 second.

This does what we would expect, first transitions brightness, then color temperature.

Now looking at the adaptive lighting [implementation](https://github.com/basnijholt/adaptive-lighting/blob/ceaddb8543295c8baefa6994547cd9cc8547749b/custom_components/adaptive_lighting/switch.py#L846-L858), it does exactly do this:
```python
# Could be a list of length 1 or 2
service_datas = _split_service_data(
    service_data, adapt_brightness, adapt_color
)
await turn_on(service_datas[0])
if len(service_datas) == 2:
    transition = service_datas[0].get(ATTR_TRANSITION)
    if transition is not None:
        await asyncio.sleep(transition)
    await turn_on(service_datas[1])
```
- If brightness and color temperature need to be set
- First set brightness
- If this call had a transition, sleep for that amount 
- Then set color temperature

So it might just work out-of-the-box after all. Let's try...

**Comment by edobez** [comment]
> I assume you are disabling AL on the on→off transition, to 'intercept' when the light is turned back on again. So you can manually set the brightness and color in a sequence with the `delayed_turn_on` script, right? 
Yes, correct. I don't want to rely on AL for the off->on transition.

> But wouldn't this disable AL for all lights under control of that AL switch?
Yes. In my case I use that AL configuration for only one light, so it's not a problem.
